//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Customer_ID { get; set; }
        public string SongName { get; set; }
        public string Artist { get; set; }
        public string RequestedBy { get; set; }
    }
}
